defmodule Aoc2025.Day07Test do
  use ExUnit.Case
  alias Aoc2025.Day07
  @puzzle_input ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"

  describe "part1/1" do
    test "part1 description" do
      assert Day07.part1(@puzzle_input) == 21
    end
  end

  describe "part2/1" do
    test "part2 description" do
      assert Day07.part2(@puzzle_input) == 40
    end
  end
end
